#include <fieldtestparser.h>
#include <iostream>

using namespace std;

// DO NOT MODIFY - This file is automatically generated during compilation.

bool FieldTestParser::updateParameters(string fname, Parameters* params){
  if(!checkId(params)){
    return false;
  }
  reader.clearData();
  ParamReader::ParamResult result = reader.readFile(fname);
  if(result != ParamReader::SUCCESS){
    cout << "An error occurred while trying to read " << fname << ".\n";
    return false;
  }
  FieldTestParameters *pars = (FieldTestParameters*) params;

  if(!reader.hasSection(string("FieldTest"))){
    return true;
  }

  if(reader.hasParameter(string("FieldTest"),string("Amplitude"))){
    double result = reader.readAsDouble(string("FieldTest"),string("Amplitude"));
    if(result <= 1.000000e+06 && result >= -1.000000e+06){
      pars->setAmplitude(result);
    }
    else{
      cout << "Parameter Amplitude out of range.\n";
    }
  }

  return true;
}

